# Generated by Django 5.0.4 on 2024-05-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_options_alter_book_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbnId', models.IntegerField()),
                ('author_title', models.CharField(max_length=30)),
                ('book_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='Books.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Books.isbn'),
        ),
    ]
